### ISSUE TITLE
I cannot get my SSL certificates, thus my page shows as unsafare http instead of https

### ISSUE THREAD

**Issue by ratarasta** [AzuraCast/.github#1]
I tried the steps from Enabling LetsEncrypt without luck.
I got this error from the weblish command page.

nginx_proxy_letsencrypt    | [Fri Sep 17 18:21:16 UTC 2021] radiopirata.co:Verify error:Invalid response from http://radiopirata.co/.well-known/acme-challenge/bPm0GN1_j4RMTbb8sHHZ0EIiL14iP3Nxw3qC0t0Op6M [184.168.131.241]: 
nginx_proxy_letsencrypt    | [Fri Sep 17 18:21:16 UTC 2021] Please check log file for more details: /dev/null
nginx_proxy_letsencrypt    | Sleep for 3600s

help please

**Comment by ItsMitchh** [comment]
This is the wrong repository for GitHub issues, check https://github.com/AzuraCast/AzuraCast/issues for more information.
